const userLogList = [
    {
        accompanyName: '카페조하',
        date: '24.03.17.',
        startTime: '09:40',
        finishTime: '09:58',
        startLoc: '이화여대 정문',
        finishLoc: '카페 아늑',
        fee: '1800',
    },
    {
        accompanyName: '카페조하',
        date: '24.03.18.',
        startTime: '09:40',
        finishTime: '09:58',
        startLoc: '이화여대 정문',
        finishLoc: '카페 아늑',
        fee: '1800',
    },
    {
        accompanyName: '카페조하',
        date: '24.03.30.',
        startTime: '09:40',
        finishTime: '09:58',
        startLoc: '이화여대 정문',
        finishLoc: '카페 아늑',
        fee: '1800',
    },
    {
        accompanyName: '카페조하',
        date: '24.04.30.',
        startTime: '09:40',
        finishTime: '09:58',
        startLoc: '이화여대 정문',
        finishLoc: '카페 아늑',
        fee: '1800',
    },
    {
        accompanyName: '카페조하',
        date: '24.04.30.',
        startTime: '09:40',
        finishTime: '09:58',
        startLoc: '이화여대 정문',
        finishLoc: '카페 아늑',
        fee: '1800',
    },
    {
        accompanyName: '카페조하',
        date: '24.04.30.',
        startTime: '09:40',
        finishTime: '09:58',
        startLoc: '이화여대 정문',
        finishLoc: '카페 아늑',
        fee: '1800',
    },
    {
        accompanyName: '카페조하',
        date: '24.04.30.',
        startTime: '09:40',
        finishTime: '09:58',
        startLoc: '이화여대 정문',
        finishLoc: '카페 아늑',
        fee: '1800',
    },
    {
        accompanyName: '카페조하',
        date: '24.04.30.',
        startTime: '09:40',
        finishTime: '09:58',
        startLoc: '이화여대 정문',
        finishLoc: '카페 아늑',
        fee: '1800',
    },
    {
        accompanyName: '카페조하',
        date: '24.04.30.',
        startTime: '09:40',
        finishTime: '09:58',
        startLoc: '이화여대 정문',
        finishLoc: '카페 아늑',
        fee: '1800',
    },
    {
        accompanyName: '카페조하',
        date: '24.04.30.',
        startTime: '09:40',
        finishTime: '09:58',
        startLoc: '이화여대 정문',
        finishLoc: '카페 아늑',
        fee: '1800',
    },
    {
        accompanyName: '카페조하',
        date: '24.05.20.',
        startTime: '09:40',
        finishTime: '09:58',
        startLoc: '이화여대 정문',
        finishLoc: '카페 아늑',
        fee: '1800',
    },
    {
        accompanyName: '카페조하',
        date: '24.05.21.',
        startTime: '09:40',
        finishTime: '09:58',
        startLoc: '이화여대 정문',
        finishLoc: '카페 아늑',
        fee: '1800',
    },
    {
        accompanyName: '카페조하',
        date: '24.05.30.',
        startTime: '09:40',
        finishTime: '09:58',
        startLoc: '이화여대 정문',
        finishLoc: '카페 아늑',
        fee: '1800',
    },
    {
        accompanyName: '카페조하',
        date: '24.05.30.',
        startTime: '09:40',
        finishTime: '09:58',
        startLoc: '이화여대 정문',
        finishLoc: '카페 아늑',
        fee: '1800',
    },
    {
        accompanyName: '카페조하',
        date: '24.05.30.',
        startTime: '09:40',
        finishTime: '09:58',
        startLoc: '이화여대 정문',
        finishLoc: '카페 아늑',
        fee: '1800',
    },
    {
        accompanyName: '카페조하',
        date: '24.05.30.',
        startTime: '09:40',
        finishTime: '09:58',
        startLoc: '이화여대 정문',
        finishLoc: '카페 아늑',
        fee: '1800',
    },
    {
        accompanyName: '카페조하',
        date: '24.05.30.',
        startTime: '09:40',
        finishTime: '09:58',
        startLoc: '이화여대 정문',
        finishLoc: '카페 아늑',
        fee: '1800',
    },
    {
        accompanyName: '카페조하',
        date: '24.05.30.',
        startTime: '09:40',
        finishTime: '09:58',
        startLoc: '이화여대 정문',
        finishLoc: '카페 아늑',
        fee: '1800',
    },
];

export default userLogList;
